method: p2s
data:
  dataset: ModelNet10
  classes: null
  scan: 42
  input_type: pointcloud
  path: /mnt/raphael/ModelNet10
  pointcloud_n: null
  pointcloud_noise: null
  points_subsample: 2048
  points_file: points.npz
  points_iou_file: points.npz
  pointcloud_file: pointcloud.npz
  voxels_file: null
  train_split: train
  val_split: test
  test_split: test
  file: null
  dim: 3 # this actually determines the input dimension of the encoder
training:
  out_dir: /mnt/raphael/ModelNet10_out/p2s/conventional
  load_model: best
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  generation_dir: mesh
  vis_n_outputs: 1000
  refine: false
  n_x: 128
  n_z: 1
  file_ending: .ply
